- id: check-autopkg-recipes
  name: Check AutoPkg Recipes
  description: This hook checks AutoPkg recipes to ensure they contain required top-level keys. (https://github.com/autopkg/autopkg/wiki/Recipe-Format)
  entry: check-autopkg-recipes
  language: python
  files: '.recipe$'
  types: [text]

- id: forbid-autopkg-overrides
  name: Forbid AutoPkg Overrides
  description: This hook prevents AutoPkg overrides from being added to the repo.
  entry: forbid-autopkg-overrides
  language: python
  files: '.recipe$'
  types: [text]

- id: check-munki-manifests
  name: Check Munki Manifests
  description: This hook checks Munki manifests to ensure they are valid.
  entry: check-munki-manifests
  language: python
  files: '/manifests/'
  types: [text]

- id: check-munki-pkgsinfo
  name: Check Munki Pkginfo Files
  description: This hook checks Munki pkginfo files to ensure they are valid.
  entry: check-munki-pkgsinfo
  language: python
  files: '/pkgsinfo/'
  types: [text]

- id: check-munkiadmin-scripts
  name: Check MunkiAdmin Scripts
  description: This hook ensures MunkiAdmin scripts are executable.
  entry: check-munkiadmin-scripts
  language: python
  files: '/MunkiAdmin/scripts/'
  types: [text]

- id: check-munkipkg-buildinfo
  name: Check MunkiPkg build-info files to ensure they are valid.
  description: This hook checks XML property list (plist) files for basic syntax errors.
  entry: check-munkipkg-buildinfo
  language: python
  files: 'build-info.(plist|yml|yaml|json)$'
  types: [text]

- id: check-plists
  name: Check Plists
  description: This hook checks XML property list (plist) files for basic syntax errors.
  entry: check-plists
  language: python
  files: '.plist$|.recipe$|.mobileconfig$|.pkginfo$'
  types: [text]

- id: munki-makecatalogs
  name: Run Munki Makecatalogs
  description: This hook runs the "makecatalogs" command to ensure all referenced packages are present.
  entry: munki-makecatalogs
  language: python
  files: '/pkgsinfo/'
  types: [text]
